#!/bin/bash
exec 2>&1

ln -sf {{pkg.path}}/dist {{pkg.svc_var_path}}
ln -sf {{pkg.path}}/node_modules {{pkg.svc_var_path}}
cp -rf {{pkg.svc_config_path}}/config.js {{pkg.svc_var_path}}/dist/config.js
